# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/designer/data.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_STARK(object):
    def setupUi(self, STARK):
        STARK.setObjectName("STARK")
        STARK.resize(800, 600)
        self.buttonBox = QtWidgets.QDialogButtonBox(STARK)
        self.buttonBox.setGeometry(QtCore.QRect(430, 540, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(STARK)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 741, 481))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_3.addWidget(self.radioButton_6)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_3)

        self.retranslateUi(STARK)
        self.buttonBox.accepted.connect(self.process)
        #self.buttonBox.rejected.connect(self.process)
        self.buttonBox.rejected.connect(STARK.reject)
        QtCore.QMetaObject.connectSlotsByName(STARK)

    def retranslateUi(self, STARK):
        _translate = QtCore.QCoreApplication.translate
        STARK.setWindowTitle(_translate("STARK", "Dialog"))
        self.label.setText(_translate("STARK", "Input"))
        self.label_2.setText(_translate("STARK", "Output"))
        self.label_3.setText(_translate("STARK", "Fixed"))
        self.radioButton.setText(_translate("STARK", "Yes"))
        self.radioButton_2.setText(_translate("STARK", "No"))
        self.label_4.setText(_translate("STARK", "Complete"))
        self.radioButton_5.setText(_translate("STARK", "Yes"))
        self.radioButton_6.setText(_translate("STARK", "No"))

    def process(self):
        print('processing...')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    STARK = QtWidgets.QDialog()
    ui = Ui_STARK()
    ui.setupUi(STARK)
    STARK.show()
    sys.exit(app.exec_())
